### ISSUE TITLE
cant handle utf8 chartacters

### ISSUE THREAD

**Issue by ewan-000** [gronank/ExportToABRIS#11]
Traceback (most recent call last):
  File "ExportToAbris.py", line 89, in <module>
  File "ExportToAbris.py", line 76, in exportToAbris
  File "exportabris.py", line 89, in Export
  File "exportabris.py", line 14, in save
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u25ed' in position 22784: character maps to <undefined>
[8588] Failed to execute script 'ExportToAbris' due to unhandled exception!

        {
            "geometry": {
                "coordinates": [
                    37.180584486445,
                    33.808557073502
                ],
                "type": "Point"
            },
            "properties": {
                "description": "CSAR: A-10C_2-Jackal 3C [◭] AJsarge<br>33 48' 30.805\"N  37 10' 50.104\"E<br>",
                "icon": "csar"
            },
            "type": "Feature"
        },

**Comment by ewan-000** [comment]
I think this just needs the encoding specified in the save function
